model_type: mlp # `mlp` or `sr`
data_files: data/test/*.jsonl

save_steps: 1000

checkpoint: ckpts/mlp-step-1000.ckpt

model_args:
  hidden_size: 64
  num_teams: 12
  num_venues: 3
  num_results: 3

trainer:
  accelerator: mps
  strategy: auto
  devices: auto
  max_steps: 18000
  accumulate_grad_batches: 32
  precision: 16-mixed
